file_format: "1"
id: stealth 
name: Stealth 
type: shield
url: https://github.com/foostan/crkbd/
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
  - underglow
  - studio
siblings:
  - stealth_left
  - stealth_right
